sense_dict = {
    'after all,':   ["Contingency.Cause+Belief.Reason+Belief","Expansion.Conjunction"],
    'after that,':  ["Temporal.Asynchronous.Succession"],
    'along with,':  ["Expansion.Conjunction"],
    'and then,':    ["Expansion.Disjunction"],
    'as a result,': ["Contingency.Cause.Result"],
    'as an alternative,': ["Expansion.Disjunction"],
    'as well,':           ["Comparison.Similarity","Expansion.Conjunction"],
    'at that point,':     ["Temporal.Synchronous"],
    'at the same time,':  ["Temporal.Synchronous"],
    'at the time,':       ["Temporal.Synchronous"],
    'but then,':          ["Comparison.Concession.Arg2-as-denier"],
    'but then again,':    ["Comparison.Concession.Arg2-as-denier"],
    'by comparison,':     ["Comparison.Contrast"],
    'by contrast,':       ["Comparison.Contrast"],
    'by the way,':        ["Comparison:Contrast","Expansion.Conjunction"],
    'by then,':            ["Temporal.Asynchronous.Succession|Contingency.Cause.Reason","Temporal.Asynchronous.Succession"],
    'even before,':        ["Temporal.Asynchronous.Precedence|Comparison.Concession.Arg1-as-denier"],
    'even before then,':   ["Temporal.Asynchronous.Succession|Comparison.Concession.Arg2-as-denier"],
    'even then,':          ["Temporal.Asynchronous.Precedence|Comparison.Concession.Arg2-as-denier"],
    'for example,':        ["Expansion.Instantiation.Arg2-as-instance"],
    'for instance,':       ["Expansion.Instantiation.Arg2-as-instance"],
    'for one,':            ["Expansion.Instantiation"],
    'for one thing,':      ["Expansion.Instantiation"],
    'in addition,':        ["Expansion.Conjunction"],
    'in any case,':        ["Comparison.Concession.Arg2-as-denier"],
    'in any event,':       ["Expansion.Conjunction","Expansion.Level-of-detail.Arg1-as-detail"],
    'in contrast,':        ["Comparison.Contrast"],
    'in essence,':         ["Expansion.Conjunction"],
    'in fact,':            ["Comparison.Concession.Arg2-as-denier","Comparison.Contrast","Expansion.Conjunction","Expansion.Instantiation.Arg2-as-instance","Expansion.Level-of-detail.Arg1-as-detail","Expansion.Level-of-detail.Arg2-as-detail"],
    'in other words,':     ["Expansion.Equivalence"],
    'in particular,':      ["Expansion.Instantiation.Arg2-as-instance","Expansion.Level-of-detail.Arg2-as-detail"],
    'in short,':           ["Expansion.Level-of-detail.Arg1-as-detail"],
    'in sum,':             ["Expansion.Level-of-detail.Arg1-as-detail"],
    'in the end,':         ["Comparison.Concession.Arg2-as-denier","Comparison.Contrast","Contingency.Cause.Result","Expansion.Conjunction","Expansion.Level-of-detail.Arg1-as-detail","Expansion.Level-of-detail.Arg2-as-detail","Temporal.Asynchronous.Precedence"],
    'in the meantime,':    ["Temporal.Asynchronous.Succession","Temporal.Synchronous|Comparison.Contrast","Temporal.Synchronous"],
    'in the meanwhile,':   ["Temporal.Synchronous"],
    'in this way,':        ["Contingency.Cause.Result"],
    'in turn,':            ["Temporal.Asynchronous.Precedence","Contingency.Cause.Result","Expansion.Conjunction","Expansion.Level-of-detail","Temporal.Asynchronous"],
    'later on,':           ["Temporal.Asynchronous.Precedence"],
    'more accurately,':    ["Expansion.Substitution.Arg2-as-subst"],
    'no matter,':          ["Comparison.Concession.Arg1-as-denier"],
    'on the contrary,':    ["Comparison.Contrast"],
    'on the other,':       ["Comparison.Concession.Arg2-as-denier","Comparison.Contrast"],
    'on the other hand,':  ["Comparison.Concession.Arg2-as-denier","Comparison.Contrast"],
    'quite the contrary,': ["Expansion.Substitution"],
    'that is,':            ["Expansion.Equivalence","Expansion.Level-of-detail.Arg2-as-detail"]
}